server:
  port: 10200
 #${random.int[10000,10100]}  
spring:
  application:
    name: config-sever  
  rabbitmq:
    host: 47.105.143.141
    port: 5672
    virtual-host: my_vhost
    username: admin
    password: admin
     
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhoumac/config-repository # 远程git仓库的地址
          username: 742042932@qq.com  # 以及相应的账户名
          password: 742042932mn  # 和密码
          search-paths: '{application}'
          basedir: E:\Java_IDEA\config\basedir  # 可以使用这个配置项来指定本地git仓库的路径
eureka:
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
        defaultZone: http://localhost:10000/eureka/