server:
  port: 8889
 #${random.int[10000,10100]}
from: order1.1 
spring:
  #rabbitmq:
   # host: 47.105.143.141
  #  port: 5672
   # virtual-host: my_vhost
  #  username: springcloudBus
   # password: 742042932   
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 47.105.143.141
                port: 5672
                username: admin
                password: admin
                virtual-host: my_vhost
      bindings:  # 服务的整合处理
        myOutput:   # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明          #producer:              #partition-key-expression: payload #分区表达式            #partition-count: 2 #消息分区数量             
          destination: firstExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置 
        myInput:
          destination: myOutput  
  redis:
    host: 47.105.143.141
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
      timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.143.141:3307/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource       
    #连接池的配置信息       
    #初始化大小，最小，最大      
    initial-size: 5
    min-idle: 5
    max-active: 50
    query-timeout: 10000
    transaction-query-timeout: 6000
    remove-abandoned-timeout: 30000
    #配置获取连接等待超时的时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    ime-between-eviction-runs-millis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: true
    test-on-return: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:
        commons-log.connection-logger-name: stat,config,wall,log4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录       
    connectionProperties: config.decrypt=false;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMMZrE1MXdiZkRj0Nx1nHiu33wmLcxVNTCYotCSpwsXEcRFfORwLQvGjj2rD9OY1XN96KxaJgWMy+darWAOH7ysCAwEAAQ==
    #打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 300
    verify-server-certificate: false
       
management:
  endpoints:
    web:
      exposure:
        include:  "*"
        
        
        