server:
  port: 10100
 #${random.int[10000,10100]}
spring:
  application:
    name: gateway
  security:
    user:
      name: admin
      password: 123456           
  redis:
    host: 47.105.143.141
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
      timeout: 1000
management:
  endpoints:
    web:
      exposure:
        include: refresh      
zhou:  
  isOpenToken: false   
          
eureka:
  instance:
    prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
      
#zuul:#  routes:
#    api-a:
#      path: /api-a/**#      serviceId: user-service
      