server:
  port: 10001
 #${random.int[10000,10100]}
spring:
  application:
    name: myeurka-server
  security:
    user:
      name: admin
      password: 123456
  freemarker:   
    preferFileSystemAcces: fasle
          
eureka: 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:10001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@localhost:10000/eureka/
      