
server:
  port:  ${random.int[10300,10400]}
 #${random.int[10000,10100]}

eureka:
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 60 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 10 # 如果现在超过了5秒的间隔（默认是90秒）
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
      
spring:
  application:
    name: stream-service  
  cloud:
    stream:      #instance-count: 2 #消费者实例总数
      #instance-index: 0 #当前消费者实例索引号
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 47.105.143.141
                port: 5672
                username: admin
                password: admin
                virtual-host: my_vhost
      bindings: # 服务的整合处理  
        myInput:          #consumer:            #partitioned: true #开启消息分区配置
                        
          destination: firstExchange
          binder: defaultRabbit
          content-type: application/json
          group: firstExchangeConsumers #分组 相同组只消费一次 消息持久化
       
       

        
        
        